export const experiences = [
  {
    highlight: "Education",
    title: "Nucamp Bootcamp",
    date: "MAR - NOV 2024",
    description: "fullstack web developer course",
    side: "left",
    icon: "graduation",
  },
  {
    highlight: "Team",
    title: "Want Some Coffee",
    date: "JUL 2024",
    description: "cafe finder web app",
    side: "left",
    icon: "team",
  },
  {
    highlight: null,
    title: "Toy project - weather app, card game, shopping mall",
    date: "AUG 2024",
    description: "simple card game",
    side: "right",
    icon: "solo",
  },
  {
    highlight: "Team",
    highlight2: "3rd Awarded",
    title: "ExploreX",
    date: "SEP 2024",
    description: "travel guide web app",
    side: "left",
    icon: "award",
  },
  {
    highlight: "Team",
    highlight2: "Hackathon",
    title: "Time tracker",
    date: "JAN 2025",
    description: "time tracking web app",
    side: "left",
    icon: "team",
  },
  {
    highlight: "Solo",
    title: "Solo Project - Netflix Clone",
    date: "DEC - FEB 2024/25",
    description: "netflix clone with tailwind",
    side: "right",
    icon: "solo",
  },
  {
    highlight: "Solo",
    title: "Solo Project - Portfolio website",
    date: "MAR 2025",
    description: "portfolio website",
    side: "right",
    icon: "solo",
  },
];
